-- FTR.NAB.CMN-0004 tech §6: the pods of agents (one per owner), the queue of
-- turns waiting for a pod and the capacity the manager works with.
-- Deviations (tech §9): agent_queue keeps the reference of the turn and the
-- time it was handed back to Kafka instead of a Kafka header; agent_capacity
-- also keeps the ceiling the manager computed, for the administration API.

-- +goose Up
CREATE SEQUENCE agent_pod_generation;

CREATE TABLE agent_pods (
  owner_id         UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  generation       BIGINT NOT NULL,
  pod              TEXT NOT NULL,
  state            TEXT NOT NULL CHECK (state IN ('starting','ready','stopping')),
  stop_reason      TEXT,
  ip               TEXT,
  node             TEXT,
  image            TEXT NOT NULL,
  warm             BOOLEAN NOT NULL DEFAULT false,
  warm_rank        INT,
  probe            BOOLEAN NOT NULL DEFAULT false,
  sessions         INT NOT NULL DEFAULT 0,
  busy             INT NOT NULL DEFAULT 0,  -- turns running; valid while busy_until is in the future
  busy_until       TIMESTAMPTZ,
  started_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  ready_at         TIMESTAMPTZ,
  last_activity_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  state_changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX agent_pods_evict ON agent_pods (warm, last_activity_at) WHERE state = 'ready';

CREATE TABLE agent_queue (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id        UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind            TEXT NOT NULL CHECK (kind IN ('message','task')),
  reason          TEXT NOT NULL CHECK (reason IN ('starting','capacity','order')),
  ref             TEXT NOT NULL,          -- the message or the task run of the turn
  topic           TEXT NOT NULL,
  key             TEXT NOT NULL,
  value           BYTEA NOT NULL,
  conversation_id UUID,
  message_id      UUID,
  channel         TEXT,
  enqueued_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  dispatched_at   TIMESTAMPTZ,            -- handed back to Kafka, not yet taken
  notified_at     TIMESTAMPTZ,
  attempts        INT NOT NULL DEFAULT 0, -- pods the turn lost
  resume          UUID,                   -- the unfinished answer the turn continues
  position        INT,
  UNIQUE (owner_id, ref)
);
CREATE INDEX agent_queue_owner ON agent_queue (owner_id, id);
CREATE INDEX agent_queue_age ON agent_queue (enqueued_at);

CREATE TABLE agent_capacity (
  id             BOOLEAN PRIMARY KEY DEFAULT true CHECK (id),
  learned_max    INT,
  learned_at     TIMESTAMPTZ,
  probe_after    TIMESTAMPTZ,
  probe_interval INTERVAL NOT NULL DEFAULT '5 minutes',
  peak_at        TIMESTAMPTZ,             -- the ceiling was last reached
  capacity_at    TIMESTAMPTZ,             -- a turn last waited for capacity
  ceiling        INT,                     -- computed by the manager; NULL: none
  source         TEXT NOT NULL DEFAULT 'none',
  warm_target    INT NOT NULL DEFAULT 0, -- -1: every owner active in the window
  updated_at     TIMESTAMPTZ
);
INSERT INTO agent_capacity DEFAULT VALUES;

ALTER TABLE harness_sessions ADD COLUMN pod_generation BIGINT, ADD COLUMN model TEXT;
UPDATE harness_sessions SET model = pod WHERE closed_at IS NULL;
-- R18: the sessions of conversations reopen in the pods of their owners
UPDATE harness_sessions SET closed_at = now() WHERE closed_at IS NULL AND run_id IS NULL;

-- +goose Down
ALTER TABLE harness_sessions DROP COLUMN model, DROP COLUMN pod_generation;
DROP TABLE agent_capacity; DROP TABLE agent_queue; DROP TABLE agent_pods;
DROP SEQUENCE agent_pod_generation;
